### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/opentelemetry-collector-contrib#1733]
Stack trace

```sh
panic: runtime error: index out of range [17] with length 17 [recovered]
	panic: runtime error: index out of range [17] with length 17

goroutine 6470 [running]:
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0x14000cf1e00, {0x0, 0x0, 0x0})
	/Users/makeavish/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.4.0/trace/span.go:346 +0x8cc
panic({0x1070031a0, 0x14004ae6a68})
	/usr/local/go/src/runtime/panic.go:1052 +0x2b0
github.com/open-telemetry/opentelemetry-collector-contrib/processor/signozspanmetricsprocessor.(*processorImp).updateLatencyMetrics(0x1400071ae00, {0x14004b90cc0, 0x3e}, 0x42b0c6f7a0b5c0fa, 0x11)
	/Users/makeavish/signoz/opentelemetry-collector-contrib/processor/signozspanmetricsprocessor/processor.go:542 +0x264
github.com/open-telemetry/opentelemetry-collector-contrib/processor/signozspanmetricsprocessor.(*processorImp).aggregateMetricsForSpan(0x1400071ae00, {0x140045a7ea0, 0x10}, {0x14004abf930}, {0x140008febe0})
	/Users/makeavish/signoz/opentelemetry-collector-contrib/processor/signozspanmetricsprocessor/processor.go:509 +0x244
github.com/open-telemetry/opentelemetry-collector-contrib/processor/signozspanmetricsprocessor.(*processorImp).aggregateMetricsForServiceSpans(0x1400071ae00, {0x140008febe0}, {0x140045a7ea0, 0x10})
	/Users/makeavish/signoz/opentelemetry-collector-contrib/processor/signozspanmetricsprocessor/processor.go:490 +0x128
github.com/open-telemetry/opentelemetry-collector-contrib/processor/signozspanmetricsprocessor.(*processorImp).aggregateMetrics(0x1400071ae00, {0x140047a9cf8})
	/Users/makeavish/signoz/opentelemetry-collector-contrib/processor/signozspanmetricsprocessor/processor.go:479 +0x130
github.com/open-telemetry/opentelemetry-collector-contrib/processor/signozspanmetricsprocessor.(*processorImp).ConsumeTraces(0x1400071ae00, {0x10741cd58, 0x14003939380}, {0x140047a9cf8})
	/Users/makeavish/signoz/opentelemetry-collector-contrib/processor/signozspanmetricsprocessor/process
ogo.opentelemetry.io/collector/model/otlpgrpc.rawTracesServer.Export({{0x1073a3520, 0x1400000c978}}, {0x10741cd58, 0x14003939260}, 0x140047a9c50)
	/Users/makeavish/go/pkg/mod/go.opentelemetry.io/collector/model@v0.45.0/otlpgrpc/traces.go:166 +0x64
go.opentelemetry.io/collector/model/internal/data/protogen/collector/trace/v1._TraceService_Export_Handler.func1({0x10741cd58, 0x14003939260}, {0x10713a720, 0x140047a9c50})
	/Users/makeavish/go/pkg/mod/go.opentelemetry.io/collector/model@v0.45.0/internal/data/protogen/collector/trace/v1/trace_service.pb.go:217 +0xbc
go.opentelemetry.io/collector/config/configgrpc.enhanceWithClientInformation.func1({0x10741cd58, 0x14003939170}, {0x10713a720, 0x140047a9c50}, 0x14004a87f60, 0x140047a9c68)
	/Users/makeavish/go/pkg/mod/go.opentelemetry.io/collector@v0.45.0/config/configgrpc/configgrpc.go:382 +0x8c
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x10741cd58, 0x14003939170}, {0x10713a720, 0x140047a9c50})
	/Users/makeavish/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1116 +0xdc
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1({0x10741cd58, 0x14003939170}, {0x10713a720, 0x140047a9c50}, 0x14004a87f60, 0x14004af0600)
	/Users/makeavish/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.28.0/interceptor.go:325 +0x5f4
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x10741cd58, 0x14003938ea0}, {0x10713a720, 0x140047a9c50})
	/Users/makeavish/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1119 +0x1cc
google.golang.org/grpc.chainUnaryInterceptors.func1({0x10741cd58, 0x14003938ea0}, {0x10713a720, 0x140047a9c50}, 0x14004a87f60, 0x140047a9c68)
	/Users/makeavish/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1121 +0x1d0
go.opentelemetry.io/collector/model/internal/data/protogen/collector/trace/v1._TraceService_Export_Handler({0x106a6ff60, 0x1400011f870}, {0x10741cd58, 0x14003938ea0}, 0x140006bf8c0, 0x14000cc8d80)
	/Users/makeavish/go/pkg/mod/go.opentelemetry.io/collector/model@v0.45.0/internal/data/protogen/collector/trace/v1/trace_service.pb.go:219 +0x1fc
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000b1b500, {0x107474bc0, 0x14004a6eea0}, 0x14003ce0b40, 0x1400067d3b0, 0x109aa7b70, 0x0)
	/Users/makeavish/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1282 +0x1254
google.golang.org/grpc.(*Server).handleStream(0x14000b1b500, {0x107474bc0, 0x14004a6eea0}, 0x14003ce0b40, 0x0)
	/Users/makeavish/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1616 +0x80c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x140079e02a0, 0x14000b1b500, {0x107474bc0, 0x14004a6eea0}, 0x14003ce0b40)
	/Users/makeavish/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:921 +0xa4
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/makeavish/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:919 +0x260
Socket connection to remote was closed
Process exiting with code: 0
```

@makeavish any chance you were sending some data which has some really big duration? Please share the max duration value in you load data.

**Comment by srikanthccv** [comment]
@makeavish this is not reproducible. It happens when the duration exceeds the last bucket here https://github.com/SigNoz/opentelemetry-collector-contrib/blob/develop/processor/signozspanmetricsprocessor/processor.go#L55, which is really big. In real world scenarios this should never happen. I am going to close this.
